server:
  servlet:
    context-path: /api/v1.0

spring:
  application:
    name: erms
  datasource:
    url: jdbc:mysql://localhost:3306/erms_app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

aws:
  access:
    key:
  secret:
    key:

jwt:
  secret:
    key: kRUYzCUYfFyAkXIp1P5NSdnXnJlZnNWYFwOUsKi3S/Y=
  expiration:
    minutes: 480
  allowed:
    clock:
      skew:
        seconds: 120

cloudinary:
  cloud-name: dajhznf3b
  api-key: 987995148325983
  api-secret: 2j4OWuQ4VhptaMTXE83Sm12ivlM


momo:
  partner-code: MOMO
  return-url: http://localhost:3000/
  end-point: https://test-payment.momo.vn/v2/gateway/api
  ipn-url: http://localhost:8080/api/momo/ipn-handler
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  request-type: captureWallet